# Generated by Django 4.0.5 on 2022-07-08 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
