# Generated by Django 4.0.5 on 2022-07-11 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_remove_user_uid_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phoneNumber',
            field=models.IntegerField(default=99999999),
            preserve_default=False,
        ),
    ]
